const Data=[{
  
    id:1,
    imgsrc:"img2.jpeg",
    link:"img2.jpeg",
    name:"swati",
   size:"small",},
   {
 
    id:2,
    imgsrc:"img3.jpeg",
    name:"s",
    link:"img3.jpeg",
    size: "large",  }  ,
    {
     id:3,
     imgsrc:"img1.jpeg",
     link:"img1.jpeg",
       size:"medium",},
    {
     id:4,
     imgsrc:"img4.jpeg",
     link:"img4.jpeg",
      size:"small",},
    {
     id:5,
     imgsrc:"img5.jpeg",
     link:"img5.jpeg",
      size:"medium",},
    { 
      id:6,
     imgsrc:"img6.jpeg",
     link:"img6.jpeg",
     size:"small",},
     {
     id:7,
    imgsrc:"img7.jpeg",
    link:"img7.jpeg",
     size:"medium",},
    {
     id:8,
    imgsrc:"img8.jpeg",
    link:"img8.jpeg",
    size:"small",},
    {
     id:9,
    imgsrc:"img9.jpeg",
    link:"img9.jpeg",
     size:"large",},
    {
     id:10,
    imgsrc:"img10.jpeg",
    link:"img10.jpeg",
     size:"medium",},
    {
     id:11,
    imgsrc:"img11.jpeg",
    link:"img11.jpeg",
     size:"large",},
     {
     id:12,
    imgsrc:"img12.jpeg",
    link: "img12.jpeg",
     size:"small",},
    {
     id:13,
    imgsrc:"img13.jpeg",
    link:"img13.jpeg",
     size:"medium",},
    {
     id:14,
    imgsrc:"img14.jpeg",
    link:"img14.jpeg",
     size:"small",},
    {
     id:15,
    imgsrc:"img15.jpeg",
    link:"img15.jpeg",
    size: "large",},
    {
     id:16,
    imgsrc:"img29.jpeg",
    link:"img29.jpeg",
    size:"small",},
    {
     id:17,
    imgsrc :"img17.jpeg",
    link:"img17.jpeg",
    size:"large",},
   {
     id:18,
    imgsrc:"img18.jpeg",
    link: "img18.jpeg",
     size:"small",},
    {
     id:19,
    imgsrc:"img27.jpeg",
    link:"img27.jpeg",
     size:"medium",},
   {
     id:20,
    imgsrc:"img19.jpeg",
    link: "img19.jpeg",
     size:"large",},
   {
     id:21,
    imgsrc:"img20.jpeg",
    link:"img20.jpeg",
    size:"medium",},
   {
     id:22,
    imgsrc:"img21.jpeg",
    link:"img21.jpeg",
     size:"medium",},
   {
     id:23,
    imgsrc:"img22.jpeg",
    link:"img22.jpeg",
    size:"large",},
   {
     id:24,
    imgsrc:"img23.jpeg",
    link:"img23.jpeg",
     size:"medium",},
   {
     id:25,
    imgsrc:"img24.jpeg",
    link:"img24.jpeg",
      size:"large",},
   {
     id:26,
    imgsrc:"img26.jpeg",
    link:"img26.jpeg",
      size:"medium",},
 ];  
 export default Data;